import React from 'react'
import { DocsThemeConfig } from 'nextra-theme-docs'

/**
 * Configuration object for the Nextra documentation theme.
 *
 * @property {JSX.Element} logo - The logo displayed in the documentation.
 * @property {object} project - Project configuration details.
 * @property {string} project.link - The URL link to the project's GitHub repository.
 * @property {string} docsRepositoryBase - The base URL for the documentation repository.
 * @property {object} footer - Configuration for the footer section of the documentation.
 * @property {string} footer.text - The text displayed in the footer.
 * @property {object} navigation - Navigation settings for the documentation.
 * @property {boolean} navigation.prev - Indicates whether the previous navigation button is enabled.
 * @property {boolean} navigation.next - Indicates whether the next navigation button is enabled.
 * @property {object} toc - Table of contents settings.
 * @property {boolean} toc.backToTop - Indicates whether a "back to top" link is provided in the table of contents.
 * @property {object} editLink - Configuration for the edit link in documentation pages.
 * @property {null} editLink.text - Text for the edit link (disabled in this configuration).
 * @property {null} editLink.component - Component for the edit link (disabled in this configuration).
 */
const config: DocsThemeConfig = {
  /**
   * The logo displayed in the documentation.
   *
   * @property {JSX.Element} logo - A JSX element representing the logo.
   */
  logo: <span>DailyInsightAI</span>,
  /**
   * Project configuration details.
   *
   * @property {string} project.link - The URL link to the project's GitHub repository.
   */
  project: {
    link: 'https://github.com/nmo-genio/dailyinsightai',
  },
  /**
   * The base URL for the documentation repository.
   *
   * This is used to create links to specific files in the documentation
   * repository, such as the "Edit this page" link.
   *
   * @property {string} docsRepositoryBase - The base URL of the documentation repository.
   */
  docsRepositoryBase: 'https://github.com/nmo-genio/dailyinsightai-docs',
  /**
   * Configuration for the footer section of the documentation.
   *
   * @property {string} footer.text - The text displayed in the footer.
   */
  footer: {
    text: 'DailyInsightAI - Personalized Journaling & Idea Management App leveraging generative AI.',
  },
  /**
   * Navigation settings for the documentation.
   *
   * @property {boolean} navigation.prev - Indicates whether the previous navigation button is enabled.
   * @property {boolean} navigation.next - Indicates whether the next navigation button is enabled.
   */
  navigation: {
    prev: false,
    next: false,
  },
  /**
   * Table of contents settings.
   *
   * @property {boolean} toc.backToTop - Indicates whether a "back to top" link is provided in the table of contents.
   */
  toc: {
    float: true,
    backToTop: true
  },
  /**
   * Disables the edit link in the top right corner of each page.
   *
   * The edit link is generated by Nextra and links to the source file of the page.
   * In this case, we don't want to allow users to edit the documentation, so we disable it.
   */
  editLink: {
    text: null,
    component: null
  }
}

/**
 * The default export of this module is a configuration object for the Nextra documentation theme.
 *
 * The configuration object is used to customize the appearance and behavior of the documentation.
 * For more information, see the Nextra documentation.
 */
export default config
